version: '3.1'

services:
  db:
    image: mysql:8.0
    container_name: gp_bot_mysql
    environment:
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
